### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tvaamorim** [tvaamorim/media-downloader#1]
Media Downloader
---
O escopo final é um programa que receba o input do usuário qual filma/serie ele gostaria de baixar e o programa deve buscar o melhor torrent no `piratebay` e realizar o download em sua pasta.
 Caso seja seriado, organizar em `\Series\Noma do seriado\{Temporada}\{Capitulo]\`
 Caso seja filme, `Movies\{Nome do filme}\`

Passo a passo
---

- [ ] Parte 1: Definir packages e receber input do usuário
  - [ ] Definir Packages que serão usadas
  - [x] Receber input do usuário
    - [x] Qual o Tipo [Serie/Filme]
    - [x] Qual Nome
      - [ ] plus: adicionar inteligencia para corrigir nome
    - [x] Se for serie: Qual a temporada?
    - [x] Se for serie: Qual o capitulo? 0 para todos

- [x] Parte 2: Busca no piratebay
  - [x] Listar todos os torrents
  - [x] Selecionar os que tem mais seeder
  - [x] Coletar as informações para download

- [ ] Parte 3: Download do arquivo
  - [ ] Criar estrutura de pastas
  - [ ] Iniciar download

- [ ] Finalizar projeto
  - [ ] Criar Readme
